/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crudjvswinggz;

import accesoadatos.PedidoDAL;

import entidades.Pedidos;
import entidades.Productos;
import java.awt.Color;

import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import utilerias.OpcionesCRUD;

/**
 *
 * @author IGABRIEL
 */
public class FrmPedidosLec extends javax.swing.JFrame {

    private OpcionesCRUD opcionesCRUD;

    //se declara originalbuttonColor 
    private Color originalButtonColor;

    /**
     * Creates new form FrmPedidosLec
     */
    public FrmPedidosLec() {

        initComponents();
        jDateChooserFechaPedido.setDateFormatString("yyyy-MM-dd");

        //se obtiene el color de los botones, en este caso todos tienen el mismo
        originalButtonColor = jBtnEliminar.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblFechaPedido = new javax.swing.JLabel();
        jbtnBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jBtnModificar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jDateChooserFechaPedido = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setTitle(" Buscar Pedido");
        setBackground(new java.awt.Color(204, 204, 255));

        jlblFechaPedido.setText("Fecha de Pedido:");

        jbtnBuscar.setBackground(new java.awt.Color(153, 153, 255));
        jbtnBuscar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnBuscarMouseExited(evt);
            }
        });
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTablePedidos.setBackground(new java.awt.Color(189, 198, 236));
        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Pedido", "Nombre Cliente", "Correo Cliente", "Producto", "Cantidad", "Nombre Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePedidos.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jTablePedidos);

        jBtnModificar.setBackground(new java.awt.Color(153, 153, 255));
        jBtnModificar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jBtnModificar.setText("Modificar");
        jBtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnModificarMouseExited(evt);
            }
        });
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jBtnEliminar.setBackground(new java.awt.Color(153, 153, 255));
        jBtnEliminar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnEliminarMouseExited(evt);
            }
        });
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnCancelar.setBackground(new java.awt.Color(153, 153, 255));
        jBtnCancelar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCancelarMouseExited(evt);
            }
        });
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jDateChooserFechaPedido.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel1.setText("Pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblFechaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60)
                        .addComponent(jDateChooserFechaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(jbtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                        .addGap(236, 236, 236))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addGap(455, 455, 455)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooserFechaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(jbtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblFechaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        opcionesCRUD = OpcionesCRUD.CREAR;
        FrmPedidosEsc frmPedidosEsc = new FrmPedidosEsc(opcionesCRUD, new Pedidos());
        frmPedidosEsc.setTitle("Crear Pedido");
        frmPedidosEsc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private Pedidos obtenerDatos() {
        Pedidos pedido = new Pedidos();

        int row = jTablePedidos.getSelectedRow();
        if (row == -1) {
            return null;
        }
        pedido.setPedidoID((int) jTablePedidos.getValueAt(row, 0));

        // Conversión correcta de la fecha desde la tabla
        java.util.Date utilDate = (java.util.Date) jTablePedidos.getValueAt(row, 1);
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        pedido.setFechaPedido(sqlDate);
        pedido.setNombreCliente(jTablePedidos.getValueAt(row, 2).toString());
        pedido.setCorreoCliente(jTablePedidos.getValueAt(row, 3).toString());
        pedido.setCantidad((int) jTablePedidos.getValueAt(row, 4));
        pedido.setProductoID((int) jTablePedidos.getValueAt(row, 5));

        Productos product = new Productos();
        product.setNombre(jTablePedidos.getValueAt(row, 6).toString());
        product.setProductoID((int) jTablePedidos.getValueAt(row, 5));
        pedido.setProductoIde(product);
        return pedido;
    }

    private Pedidos obtenerDatosFecha() {
        Pedidos pedido = new Pedidos();
        Date fechaPedido = jDateChooserFechaPedido.getDate();

        if (fechaPedido == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        pedido.setFechaPedido(fechaPedido);
        return pedido;
    }

    //BOTONES
    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed


    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        // TODO add your handling code here:
        int row = jTablePedidos.getSelectedRow();
        if (row != -1) {
            opcionesCRUD = OpcionesCRUD.MODIFICAR;

            FrmPedidosEsc frmPedidosEsc = new FrmPedidosEsc(opcionesCRUD, obtenerDatos());
            frmPedidosEsc.setTitle("Modificar pedido");
            frmPedidosEsc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccionar una fila", "Pedido",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
        int row = jTablePedidos.getSelectedRow();
        if (row != -1) {
            opcionesCRUD = OpcionesCRUD.ELIMINAR;
            FrmPedidosEsc frmProductosEsc = new FrmPedidosEsc(opcionesCRUD, obtenerDatos());
            frmProductosEsc.setTitle("Eliminar pedido");
            frmProductosEsc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccionar una fila", "pedido",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jBtnEliminarActionPerformed


    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            Pedidos pedidoBusqueda = obtenerDatosFecha();
            Date fechaPedido = (pedidoBusqueda != null) ? pedidoBusqueda.getFechaPedido() : null;

            ArrayList<Pedidos> pedidos = PedidoDAL.buscar(fechaPedido);

            String[] columnas = {"ID Pedido", "Fecha Pedido", "Nombre Cliente", "Correo Cliente", "Cantidad", "ID Producto", "Nombre Producto"};
            Object[][] datos = new Object[pedidos.size()][7];
            for (int i = 0; i < pedidos.size(); i++) {
                Pedidos pedido = pedidos.get(i);
                datos[i][0] = pedido.getPedidoID();
                datos[i][1] = pedido.getFechaPedido();
                datos[i][2] = pedido.getNombreCliente();
                datos[i][3] = pedido.getCorreoCliente();
                datos[i][4] = pedido.getCantidad();
                datos[i][5] = pedido.getProductoID();
                datos[i][6] = pedido.getProductoIde().getNombre();
            }

            DefaultTableModel modelTable = new DefaultTableModel(datos, columnas);
            jTablePedidos.setModel(modelTable);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al realizar la búsqueda.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jBtnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarMouseEntered
        jBtnEliminar.setBackground(Color.RED);
    }//GEN-LAST:event_jBtnEliminarMouseEntered

    private void jBtnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelarMouseEntered
        jBtnCancelar.setBackground(Color.GRAY);
    }//GEN-LAST:event_jBtnCancelarMouseEntered

    private void jbtnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBuscarMouseEntered
        jbtnBuscar.setBackground(Color.lightGray);
    }//GEN-LAST:event_jbtnBuscarMouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(Color.PINK);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(originalButtonColor);
    }//GEN-LAST:event_jButton1MouseExited

    private void jbtnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBuscarMouseExited
        jbtnBuscar.setBackground(originalButtonColor);
    }//GEN-LAST:event_jbtnBuscarMouseExited

    private void jBtnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnModificarMouseExited
        jBtnModificar.setBackground(originalButtonColor);
    }//GEN-LAST:event_jBtnModificarMouseExited

    private void jBtnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarMouseExited
        jBtnEliminar.setBackground(originalButtonColor);
    }//GEN-LAST:event_jBtnEliminarMouseExited

    private void jBtnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelarMouseExited
        jBtnCancelar.setBackground(originalButtonColor);
    }//GEN-LAST:event_jBtnCancelarMouseExited

    private void jBtnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnModificarMouseEntered
        jBtnModificar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jBtnModificarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPedidosLec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPedidosLec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPedidosLec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPedidosLec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPedidosLec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooserFechaPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JLabel jlblFechaPedido;
    // End of variables declaration//GEN-END:variables
}
