/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crudjvswinggz;

import accesoadatos.PedidoDAL;
import accesoadatos.ProductoDAL;
import entidades.Pedidos;
import entidades.Productos;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilerias.OpcionesCRUD;

/**
 *
 * @author IGABRIEL
 */
public class FrmPedidosLec extends javax.swing.JFrame {

    private OpcionesCRUD opcionesCRUD;

    /**
     * Creates new form FrmPedidosLec
     */
    public FrmPedidosLec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblFechaPedido = new javax.swing.JLabel();
        jForTextFechaPedido = new javax.swing.JFormattedTextField();
        jbtnBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jBtnModificar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setTitle(" Buscar Pedido");

        jlblFechaPedido.setText("Fecha de Pedido:");

        jForTextFechaPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha Pedido", "Nombre Cliente", "Correo Cliente", "Producto", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePedidos);

        jBtnModificar.setText("Modificar");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblFechaPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jForTextFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jForTextFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBuscar)
                    .addComponent(jlblFechaPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        opcionesCRUD = OpcionesCRUD.CREAR;
        FrmPedidosEsc frmPedidosEsc = new FrmPedidosEsc(opcionesCRUD, new Pedidos());
        frmPedidosEsc.setTitle("Crear Pedido");
        frmPedidosEsc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private Pedidos obtenerDatos() {
        Pedidos pedido = new Pedidos();
        int row = jTablePedidos.getSelectedRow();
        if (row == -1) {
            return null;
        }
        pedido.setPedidoID((int) jTablePedidos.getValueAt(row, 0));

        // Conversión correcta de la fecha desde la tabla
        java.util.Date utilDate = (java.util.Date) jTablePedidos.getValueAt(row, 1);
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        pedido.setFechaPedido(sqlDate);
        pedido.setNombreCliente(jTablePedidos.getValueAt(row, 2).toString());
        pedido.setCorreoCliente(jTablePedidos.getValueAt(row, 3).toString());
        pedido.setCantidad((int) jTablePedidos.getValueAt(row, 4));
        pedido.setProductoID((int) jTablePedidos.getValueAt(row, 5));

        Productos product = new Productos();
        product.setNombre(jTablePedidos.getValueAt(row, 6).toString());
        product.setProductoID((int) jTablePedidos.getValueAt(row, 5));
        pedido.setProductoIde(product);
        return pedido;
    }

    private Pedidos obtenerDatosFecha() {
        Pedidos pedido = new Pedidos();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String fechaTexto = jForTextFechaPedido.getText().trim();
        if (fechaTexto.isEmpty()) {
            return null; // Retorna null si el campo de fecha está vacío
        }

        try {
            Date fechaPedido = dateFormat.parse(fechaTexto);
            pedido.setFechaPedido(fechaPedido);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Debe ser yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
            return null; // Retorna null si el formato de la fecha es incorrecto
        }

        return pedido;
    }

    //BOTONES
    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed


    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        // TODO add your handling code here:
        int row = jTablePedidos.getSelectedRow();
        if (row != -1) {
            opcionesCRUD = OpcionesCRUD.MODIFICAR;
            
            FrmPedidosEsc frmPedidosEsc = new FrmPedidosEsc(opcionesCRUD, obtenerDatos());
            frmPedidosEsc.setTitle("Modificar pedido");
            frmPedidosEsc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccionar una fila", "Pedido",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
        int row = jTablePedidos.getSelectedRow();
        if (row != -1) {
            opcionesCRUD = OpcionesCRUD.ELIMINAR;
            FrmPedidosEsc frmProductosEsc = new FrmPedidosEsc(opcionesCRUD, obtenerDatos());
            frmProductosEsc.setTitle("Eliminar pedido");
            frmProductosEsc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccionar una fila", "pedido",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jBtnEliminarActionPerformed
    private void cargarPedidos() {
        ArrayList<Pedidos> pedidos = PedidoDAL.buscar(null);

    String[] columnas = {"ID Pedido", "Fecha Pedido", "Nombre Cliente", "Correo Cliente", "Cantidad", "Nombre Producto"};
    Object[][] datos = new Object[pedidos.size()][6];
    for (int i = 0; i < pedidos.size(); i++) {
        Pedidos pedido = pedidos.get(i);
        datos[i][0] = pedido.getPedidoID();
        datos[i][1] = pedido.getFechaPedido();
        datos[i][2] = pedido.getNombreCliente();
        datos[i][3] = pedido.getCorreoCliente();
        datos[i][4] = pedido.getCantidad();
        datos[i][5] = pedido.getProductoIde().getNombre();
    }

    DefaultTableModel modelTable = new DefaultTableModel(datos, columnas);
    jTablePedidos.setModel(modelTable);
    }

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            Pedidos pedidoBusqueda = obtenerDatosFecha();
            Date fechaPedido = (pedidoBusqueda != null) ? pedidoBusqueda.getFechaPedido() : null;

            ArrayList<Pedidos> pedidos = PedidoDAL.buscar(fechaPedido);

            String[] columnas = {"ID Pedido", "Fecha Pedido", "Nombre Cliente", "Correo Cliente", "Cantidad", "ID Producto", "Nombre Producto"};
            Object[][] datos = new Object[pedidos.size()][7];
            for (int i = 0; i < pedidos.size(); i++) {
                Pedidos pedido = pedidos.get(i);
                datos[i][0] = pedido.getPedidoID();
                datos[i][1] = pedido.getFechaPedido();
                datos[i][2] = pedido.getNombreCliente();
                datos[i][3] = pedido.getCorreoCliente();
                datos[i][4] = pedido.getCantidad();
                datos[i][5] = pedido.getProductoID();
                datos[i][6] = pedido.getProductoIde().getNombre();
            }

            DefaultTableModel modelTable = new DefaultTableModel(datos, columnas);
            jTablePedidos.setModel(modelTable);
            cargarPedidos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al realizar la búsqueda.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPedidosLec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPedidosLec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPedidosLec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPedidosLec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPedidosLec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jForTextFechaPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JLabel jlblFechaPedido;
    // End of variables declaration//GEN-END:variables
}
